# Generated by Django 4.1.7 on 2023-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumnosCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadeblog',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
