# Generated by Django 4.1.7 on 2023-03-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlumnosCoder', '0003_alter_entradadeblog_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradadeblog',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entradadeblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entradas'),
        ),
    ]
